# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

container: 
  image: ubuntu:18.04

steps:
- task: CmdLine@2
  inputs:
    script: |
      sudo apt-get update
      sudo apt-get install -y ca-certificates
      sudo update-ca-certificates
- task: ArtifactoryGenericDownload@2
  inputs:
    connection: 'barb3-aol'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "generic-local/tfs-sanity/a1.in*",
            "target": "files1/39/",
            "flat": "true"
          }
        ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    failNoOp: false