# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

container: 
  image: 'windows-2019'

pool:
  vmImage: 'mcr.microsoft.com/windows/servercore:ltsc2019'

steps:
- task: ArtifactoryGenericDownload@2
  inputs:
    connection: 'ecosys-artifactory'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "generic-local/tfs-sanity/a1.in*",
            "target": "files1/39/",
            "flat": "true"
          }
        ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    failNoOp: false